// GENERATED by make_geodata_headers.py - DO NOT EDIT.
// Source: geodata/dxcc_grids.json (version 20260924_225954, content 231d2ad487a0), built 2026-09-24.
// Part of JTDX_CONTEST, Tihomir Sokcevic CE3TSK.  The generator is GPL v3; the DATA is
// derived from public-domain sources and no rights are claimed over it - geodata/README.md.

#ifndef JTDX_GEODATA_DXCC_GRIDS_DATA_H
#define JTDX_GEODATA_DXCC_GRIDS_DATA_H

#include <cstdint>
#include <cstddef>

namespace geodata {
namespace dxcc {

const std::size_t entityCount = 346;      // DXCC entities, as cty.dat lists them
const std::size_t gridCount   = 15859;      // entity-square pairs, sorted within each entity

extern const char* const prefix[];        // cty.dat primary prefix, e.g. "CE", "VP8/o"
extern const char* const name[];          // "Chile"
extern const std::uint8_t source[];       // index into sourceName[]
extern const std::uint8_t group[];        // index into groupName[]; 0 = the entity is in no group
extern const char* const groupName[];     // "", "US", "RU", ... - one administration, several entities
extern const std::size_t groupCount;
extern const char* const sourceName[];    // poly, admin1, islands, point, split, sovereign
extern const std::uint32_t offset[];      // entityCount + 1 offsets into grid[]
extern const std::uint16_t grid[];        // packed squares

extern const char* const version;         // the table's own stamp, e.g. "20260924_190143"
extern const char* const content;         // sha256 of the rows it was generated from

}  // namespace dxcc
}  // namespace geodata
#endif
