// Geographic lookups compiled into the program: which grid squares a DXCC entity occupies, and
// which US state(s) a grid square covers.  No file is read, nothing is parsed, nothing can fail at
// run time - the tables are in dxcc_grids_data.cpp and grid_states_data.cpp, generated by
// make_geodata_headers.py, which sits beside this file, from the *.json beside it too.  README.md
// here says how to regenerate and check them; the geography they were cut from, and how far each
// row can be trusted (the per-entity `source`), is documented in the author's work tree.
//
// Part of JTDX_CONTEST.  Copyright (C) 2026 Tihomir Sokcevic CE3TSK.  This program is free software:
// you may redistribute it and/or modify it under the terms of the GNU General Public License as
// published by the Free Software Foundation, either version 3 or (at your option) any later version.
// It is distributed WITHOUT ANY WARRANTY.
//
// Plain C++ on purpose - no Qt - so the tables can be exercised by a standalone test.  Everything
// here is read-only and safe to call from any thread.

#ifndef JTDX_GEODATA_H
#define JTDX_GEODATA_H

#include <cstdint>
#include <cstddef>

namespace geodata
{
  const std::uint16_t InvalidGrid = 0xffff;

  // "FF46" -> a packed square, or InvalidGrid if it is not a 4-character Maidenhead square.  Takes
  // the first four characters of a longer locator, so "FF46mi" is accepted as "FF46".
  // UPPER CASE only, as FT8 messages are: "ff46" is rejected.
  std::uint16_t packGrid (char const * grid);
  // The reverse; writes five bytes (four plus a NUL) into `out` - or, for a code no square has
  // (including InvalidGrid), just the NUL, leaving `out` an empty string.
  void unpackGrid (std::uint16_t code, char * out);

  // The eight neighbours of a square plus the square itself, written into `out` (nine entries, the
  // count returned).  Longitude wraps at the antimeridian; latitude does not go past the poles.
  // This is the tolerance a plausibility test wants: one square is 110-220 km wide.
  std::size_t gridNeighbours (std::uint16_t code, std::uint16_t * out);

  // ---- DXCC entity -> its grid squares -------------------------------------------------------
  // The index of a cty.dat primary prefix ("CE", "VP8/o"), or -1.  Case is ignored (ASCII): the
  // program's own CountryDat upper-cases the master prefix it returns, while cty.dat spells
  // twenty-nine of them with a lower-case suffix, and an unmatched prefix is never judged at all.
  int entityIndex (char const * primaryPrefix);
  char const * entityName (int entity);          // "Chile", or nullptr
  char const * entityPrefix (int entity);        // "CE", "VP8/o" - cty.dat's own spelling, or nullptr
  char const * entitySource (int entity);        // "poly", "point", ... - how good the row is
  // Entities under one administration: "US" covers K, KL, KH6, KP4 and the rest; "RU" covers
  // European and Asiatic Russia and Kaliningrad.  "" when the entity is in no group.  DXCC counts
  // these apart - that is what DXCC is for - but a station of one may transmit from another.
  char const * entityGroup (int entity);
  std::size_t entityGridCount (int entity);
  bool entityHasGrid (int entity, std::uint16_t grid);            // binary search

  // The question the decode-plausibility check asks: could a station of this entity be in this
  // square?  Defaults are the permissive ones a plausibility test wants:
  //   tolerant    - also accept the eight neighbouring squares (a square is only 110-220 km wide)
  //   sameAdmin   - also accept any square of the entity's administration group, so a KL7 holder in
  //                 Ohio or an Asiatic-Russia call west of the Urals is not called impossible.
  //                 Measured over a month of logs: halves the real decodes this test would reject
  //                 (153 -> 78) and costs 17 of 606 false detections, which the other conditions
  //                 catch anyway.  Pass false for DXCC-exact behaviour.
  // An unknown entity, an unparsable grid or an entity with no squares answers true - the test must
  // never reject what it cannot judge.
  bool gridFitsEntity (char const * primaryPrefix, char const * grid,
                       bool tolerant = true, bool sameAdmin = true);

  // ---- grid square -> US state(s) ------------------------------------------------------------
  struct StateShare
  {
    char const * code;      // "CA"
    float population;       // share of the square's people, 0..1
    float area;             // share of the square's area, 0..1
  };
  // Up to `max` states of a square, biggest share of the POPULATION first; the count returned.
  // A square outside the United States - and an unparsable or lower-case grid - gives 0, so 0 means
  // "no answer here", not "no states".  Today the busiest square holds five (FN32).
  std::size_t statesOfGrid (char const * grid, StateShare * out, std::size_t max);
  std::uint32_t gridPopulation (char const * grid);      // people living in that square, 0 if none

  // ---- provenance ----------------------------------------------------------------------------
  char const * dxccVersion ();     // "20260924_190143" - the table's own stamp
  char const * dxccContent ();     // sha256 of the rows it came from
  char const * statesVersion ();
  char const * statesContent ();
}

#endif
