// GENERATED by make_geodata_headers.py - DO NOT EDIT.
// Source: geodata/grid_states.json (version 20260924_225940, content 893707096b13), built 2026-09-24.
// Part of JTDX_CONTEST, Tihomir Sokcevic CE3TSK.  The generator is GPL v3; the DATA is
// derived from public-domain sources and no rights are claimed over it - geodata/README.md.

#ifndef JTDX_GEODATA_GRID_STATES_DATA_H
#define JTDX_GEODATA_GRID_STATES_DATA_H

#include <cstdint>
#include <cstddef>

namespace geodata {
namespace states {

const std::size_t squareCount = 723;      // grid squares that any of the 50 states touches
const std::size_t entryCount  = 1005;      // square-state entries, biggest share first

extern const char* const code[];          // the 50 two-letter codes, sorted
extern const std::size_t codeCount;
extern const std::uint16_t square[];      // packed squares, ascending - binary search this
extern const std::uint32_t population[];  // people living in that square
extern const std::uint32_t offset[];      // squareCount + 1 offsets into entry arrays
extern const std::uint8_t entryState[];   // index into code[]
extern const std::uint8_t entryPop[];     // share of the square's people, in 1/255
extern const std::uint8_t entryArea[];    // share of the square's area, in 1/255

extern const char* const version;
extern const char* const content;

}  // namespace states
}  // namespace geodata
#endif
