// GENERATED by make_geodata_headers.py - DO NOT EDIT.
// Source: geodata/grid_states.json (version 20261003_035646, content edcaca2ab6d6), built 2026-10-03.
// Part of JTDX_CONTEST, Tihomir Sokcevic CE3TSK.  The generator is GPL v3; the DATA is
// derived from public data - cty.dat (MIT licence), Natural Earth and the US Census (public
// domain) - and no rights of its own are claimed over it - geodata/README.md.

#ifndef JTDX_GEODATA_GRID_STATES_DATA_H
#define JTDX_GEODATA_GRID_STATES_DATA_H

#include <cstdint>
#include <cstddef>

namespace geodata {
namespace states {

const std::size_t squareCount = 722;      // grid squares that any of the 50 states touches
const std::size_t entryCount  = 1004;      // square-state entries, biggest share first

extern const char* const code[];          // the 50 two-letter codes, sorted
extern const std::size_t codeCount;
extern const std::uint16_t square[];      // packed squares, ascending - binary search this
extern const std::uint32_t population[];  // people living in that square
extern const std::uint32_t offset[];      // squareCount + 1 offsets into entry arrays
extern const std::uint8_t entryState[];   // index into code[]
extern const std::uint8_t entryPop[];     // share of the square's people, in 1/255
extern const std::uint8_t entryArea[];    // share of the square's area, in 1/255

extern const char* const version;
extern const char* const content;

}  // namespace states
}  // namespace geodata
#endif
