#!/usr/bin/env python3
"""Turn geodata/*.json into C++ the program compiles in, so nothing is parsed at run time.

Part of JTDX_CONTEST.  Copyright (C) 2026 Tihomir Sokcevic CE3TSK.  GPL v3 or later, WITHOUT ANY
WARRANTY.

    python3 tools/make_geodata_headers.py      # from the work tree: writes both program trees
    python3 make_geodata_headers.py            # from a geodata/ folder: writes that folder

Writes into jtdx_contest/geodata/ (and the same files into src/geodata/, the two trees stay in step):

    dxcc_grids_data.h/.cpp    346 DXCC entities -> the grid squares they occupy
    grid_states_data.h/.cpp   4-character grid square -> the US state(s) it covers
    geodata.h/.cpp            the small hand-written API over both

A 4-character square is one of 18 x 18 x 10 x 10 = 32 400 values, so every square is a uint16:

    code = ((fieldLon * 18 + fieldLat) * 10 + squareLon) * 10 + squareLat

The arrays live in the .cpp files, not the headers: a `static const` array in a header is duplicated
in every translation unit that includes it, and this is 35 KB of data.

Verifying the result is geodata_check.py's job (test/ in the work tree, beside this file in the
program trees): it compiles what this writes and compares it
with the json entity by entity and square by square.  This script only writes.
"""
import os, json, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
if os.path.exists(os.path.join(HERE, 'dxcc_grids.json')):
    ROOT = HERE                       # run from inside a geodata/ folder: read and write here
    SRC, OUTS = HERE, [HERE]
else:                                  # run from the work tree: read geodata/, write both trees
    ROOT = os.path.dirname(HERE)
    SRC  = os.path.join(ROOT, 'geodata')
    OUTS = [os.path.join(ROOT, 'jtdx_contest', 'geodata'), os.path.join(ROOT, 'src', 'geodata')]
FIELDS = 18

def pack(g):
    """'FF46' -> 0..32399, or -1 if it is not a 4-character square."""
    if len(g) != 4 or not ('A' <= g[0] <= 'R') or not ('A' <= g[1] <= 'R') \
       or not g[2].isdigit() or not g[3].isdigit():
        return -1
    return (((ord(g[0]) - 65) * FIELDS + (ord(g[1]) - 65)) * 10 + int(g[2])) * 10 + int(g[3])

def unpack(code):
    lat = code % 10; code //= 10
    lon = code % 10; code //= 10
    return chr(65 + code // FIELDS) + chr(65 + code % FIELDS) + str(lon) + str(lat)

def c_str(s): return '"%s"' % s.replace('\\', '\\\\').replace('"', '\\"')

def rows(values, per_line=16, width=6):
    out, line = [], []
    for v in values:
        line.append(('%' + str(width) + 's') % v)
        if len(line) == per_line:
            out.append(', '.join(line)); line = []
    if line: out.append(', '.join(line))
    return ',\n  '.join(out)

# The banner names no directory: this script ships in three places (tools/ in the work tree,
# geodata/ in each program tree) and a path here was wrong in two of them (review 2026-09-24).
BANNER = ('// GENERATED by make_geodata_headers.py - DO NOT EDIT.\n'
          '// Source: geodata/%s (version %s, content %s), built %s.\n'
          '// Part of JTDX_CONTEST, Tihomir Sokcevic CE3TSK.  The generator is GPL v3; the DATA is\n'
          '// derived from public-domain sources and no rights are claimed over it - geodata/README.md.\n')

def write(path, text):
    # Always UTF-8, never the locale's default: under LC_ALL=C this used to die reading a non-ASCII
    # entity name back, and on Windows it would have written cp1252 bytes into a UTF-8 source file.
    old = None
    if os.path.exists(path):
        with open(path, encoding='utf-8') as fh: old = fh.read()
    if old != text:
        with open(path, 'w', encoding='utf-8') as fh: fh.write(text)
    return old != text

# ---------------------------------------------------------------- dxcc entities -> squares
with open(os.path.join(SRC, 'dxcc_grids.json'), encoding='utf-8') as fh: dx = json.load(fh)
ents = dx['entities']
order = sorted(ents)                               # by primary prefix, so the index is stable
SOURCES = ['poly', 'admin1', 'islands', 'point', 'split', 'sovereign']
groups = [''] + sorted({v.get('group', '') for v in ents.values()} - {''})   # '' = no group, index 0
grids, offs, bad = [], [0], []
for p in order:
    for g in ents[p]['grids']:
        c = pack(g)
        if c < 0: bad.append((p, g))
        grids.append(c)
    offs.append(len(grids))
if bad: raise SystemExit('FAILED: not a 4-character square: %s' % bad[:5])
for i, p in enumerate(order):                      # each entity's squares must be sorted for bsearch
    if grids[offs[i]:offs[i+1]] != sorted(grids[offs[i]:offs[i+1]]):
        raise SystemExit('FAILED: %s squares are not sorted' % p)

dxh = (BANNER % ('dxcc_grids.json', dx['version'], dx['content'], dx['built'])) + '''
#ifndef JTDX_GEODATA_DXCC_GRIDS_DATA_H
#define JTDX_GEODATA_DXCC_GRIDS_DATA_H

#include <cstdint>
#include <cstddef>

namespace geodata {
namespace dxcc {

const std::size_t entityCount = %d;      // DXCC entities, as cty.dat lists them
const std::size_t gridCount   = %d;      // entity-square pairs, sorted within each entity

extern const char* const prefix[];        // cty.dat primary prefix, e.g. "CE", "VP8/o"
extern const char* const name[];          // "Chile"
extern const std::uint8_t source[];       // index into sourceName[]
extern const std::uint8_t group[];        // index into groupName[]; 0 = the entity is in no group
extern const char* const groupName[];     // "", "US", "RU", ... - one administration, several entities
extern const std::size_t groupCount;
extern const char* const sourceName[];    // poly, admin1, islands, point, split, sovereign
extern const std::uint32_t offset[];      // entityCount + 1 offsets into grid[]
extern const std::uint16_t grid[];        // packed squares

extern const char* const version;         // the table's own stamp, e.g. "20260924_190143"
extern const char* const content;         // sha256 of the rows it was generated from

}  // namespace dxcc
}  // namespace geodata
#endif
''' % (len(order), len(grids))

dxc = (BANNER % ('dxcc_grids.json', dx['version'], dx['content'], dx['built'])) + '''
#include "dxcc_grids_data.h"

namespace geodata {
namespace dxcc {

const char* const version = %s;
const char* const content = %s;

const char* const sourceName[] = {%s};

const char* const groupName[] = {%s};
const std::size_t groupCount = %d;

const std::uint8_t group[] = {
  %s
};

const char* const prefix[] = {
  %s
};

const char* const name[] = {
  %s
};

const std::uint8_t source[] = {
  %s
};

const std::uint32_t offset[] = {
  %s
};

const std::uint16_t grid[] = {
  %s
};

}  // namespace dxcc
}  // namespace geodata
''' % (c_str(dx['version']), c_str(dx['content']),
       ', '.join(c_str(s) for s in SOURCES),
       ', '.join(c_str(g) for g in groups), len(groups),
       rows([groups.index(ents[p].get('group', '')) for p in order], 24, 2),
       rows([c_str(p) for p in order], 6, 10),
       rows([c_str(ents[p]['name']) for p in order], 4, 30),
       rows([SOURCES.index(ents[p]['source']) for p in order], 24, 2),
       rows(offs, 12, 7),
       rows(grids, 16, 6))

# ---------------------------------------------------------------- grid square -> US states
with open(os.path.join(SRC, 'grid_states.json'), encoding='utf-8') as fh: gs = json.load(fh)
squares = gs['squares']
codes = sorted((pack(g), g) for g in squares)
states = sorted({e['s'] for v in squares.values() for e in v['states']})
sq, pop, soff, ent = [], [], [0], []
badsq = [g for _, g in codes if pack(g) < 0]
if badsq: raise SystemExit('FAILED: not a 4-character square: %s' % badsq[:5])
for code, g in codes:
    sq.append(code); pop.append(squares[g]['pop'])
    for e in squares[g]['states']:
        # Clamp into the byte these become.  Unclamped, a share of 1.004 emitted 256 into a
        # uint8_t array: a narrowing error at best, a silently wrong table at worst (review).
        p8 = min(255, max(0, int(round(e['p'] * 255))))
        a8 = min(255, max(0, int(round(e['a'] * 255))))
        if not (0.0 <= e['p'] <= 1.001 and 0.0 <= e['a'] <= 1.001):
            raise SystemExit('FAILED: %s %s has a share outside 0..1: %s %s' % (g, e['s'], e['p'], e['a']))
        ent.append((states.index(e['s']), p8, a8))
    soff.append(len(ent))
if sq != sorted(sq): raise SystemExit('FAILED: the square list is not ascending (C++ binary-searches it)')
if len(set(sq)) != len(sq): raise SystemExit('FAILED: a square is listed twice')
if any(c < 0 or c >= FIELDS * FIELDS * 100 for c in sq + grids):
    raise SystemExit('FAILED: a packed square is out of range')
if order != sorted(order):
    raise SystemExit('FAILED: the entity prefixes are not sorted (C++ binary-searches them)')
# entityIndex falls back to a case-insensitive scan when the exact search misses, because the
# program's own resolver upper-cases the prefix it hands over.  That is only unambiguous while no
# two prefixes differ by case alone - pinned here rather than assumed (review 2026-09-24).
low = {}
for p in order:
    if p.lower() in low:
        raise SystemExit('FAILED: %r and %r differ only by case - entityIndex could not tell them '
                         'apart' % (low[p.lower()], p))
    low[p.lower()] = p

gsh = (BANNER % ('grid_states.json', gs['version'], gs['content'], gs['built'])) + '''
#ifndef JTDX_GEODATA_GRID_STATES_DATA_H
#define JTDX_GEODATA_GRID_STATES_DATA_H

#include <cstdint>
#include <cstddef>

namespace geodata {
namespace states {

const std::size_t squareCount = %d;      // grid squares that any of the 50 states touches
const std::size_t entryCount  = %d;      // square-state entries, biggest share first

extern const char* const code[];          // the 50 two-letter codes, sorted
extern const std::size_t codeCount;
extern const std::uint16_t square[];      // packed squares, ascending - binary search this
extern const std::uint32_t population[];  // people living in that square
extern const std::uint32_t offset[];      // squareCount + 1 offsets into entry arrays
extern const std::uint8_t entryState[];   // index into code[]
extern const std::uint8_t entryPop[];     // share of the square's people, in 1/255
extern const std::uint8_t entryArea[];    // share of the square's area, in 1/255

extern const char* const version;
extern const char* const content;

}  // namespace states
}  // namespace geodata
#endif
''' % (len(sq), len(ent))

gsc = (BANNER % ('grid_states.json', gs['version'], gs['content'], gs['built'])) + '''
#include "grid_states_data.h"

namespace geodata {
namespace states {

const char* const version = %s;
const char* const content = %s;

const char* const code[] = {
  %s
};
const std::size_t codeCount = %d;

const std::uint16_t square[] = {
  %s
};

const std::uint32_t population[] = {
  %s
};

const std::uint32_t offset[] = {
  %s
};

const std::uint8_t entryState[] = {
  %s
};

const std::uint8_t entryPop[] = {
  %s
};

const std::uint8_t entryArea[] = {
  %s
};

}  // namespace states
}  // namespace geodata
''' % (c_str(gs['version']), c_str(gs['content']),
       rows([c_str(s) for s in states], 10, 6), len(states),
       rows(sq, 16, 6), rows(pop, 10, 9), rows(soff, 12, 7),
       rows([e[0] for e in ent], 24, 3), rows([e[1] for e in ent], 24, 4),
       rows([e[2] for e in ent], 24, 4))

changed = []
for out in OUTS:
    os.makedirs(out, exist_ok=True)
    for fn, txt in (('dxcc_grids_data.h', dxh), ('dxcc_grids_data.cpp', dxc),
                    ('grid_states_data.h', gsh), ('grid_states_data.cpp', gsc)):
        if write(os.path.join(out, fn), txt): changed.append(os.path.join(out, fn))
print('dxcc : %d entities, %d squares, %.1f KB of uint16' % (len(order), len(grids), len(grids) * 2 / 1024))
print('states: %d squares, %d entries, %.1f KB' % (len(sq), len(ent), (len(sq) * 6 + len(ent) * 3) / 1024))
print('written to: %s' % ', '.join(OUTS))
print('changed: %s' % (', '.join(os.path.relpath(c, ROOT) for c in changed) if changed else 'nothing'))
# ROOT is set in BOTH branches above: with only the work-tree branch defining it, this line raised
# NameError the first time a run from a geodata/ folder actually changed a file (review 2026-09-24)
